- .github/workflows/ci.yml
- README.md
> fix: ci target branch 수정

- src/components/global/TopNavigationBar/index.module.scss
- src/components/global/TopNavigationBar/index.tsx
- src/components/global/TopNavigationMenu/index.module.scss
- src/components/global/TopNavigationMenu/index.tsx
- src/styles/global.scss
- src/styles/variables.scss
> feat: dnd about페이지의 sub navigation을 구현하라

- src/components/atoms/EventStatusBadge/index.module.scss
- src/components/atoms/EventStatusBadge/index.tsx
- src/components/pages/HomePage/index.tsx
- src/styles/variables.scss
> feat: 공통 EventStatusBadge 컴포넌트를 구현하라

- .eslintrc.js
- src/components/atoms/Button/index.module.scss
- src/components/atoms/Button/index.test.tsx
- src/components/atoms/Button/index.tsx
- src/components/pages/HomePage/index.tsx
> feat: 버튼, link  공통 컴포넌트를 구현하라

- src/components/global/TopNavigationMenu/index.module.scss
- src/components/global/TopNavigationMenu/index.tsx
> fix: top 네이게이션 바의 sub 메뉴 hover시 정상적으로 동작하지 않는 이슈를 수정하라

- .github/workflows/ci.yml
- storybook chromatic publish ci 세팅
> ci: storybook chromatic publish ci 세팅

- src/components/global/TopNavigationBar/TopNavigationBar.stories.tsx
> style: 컴포넌트 TopNavigationBar storybook 반영

- README.md
> docs: storybook badge 추가

- README.md
- src/components/atoms/SectionTitle/index.module.scss
- src/components/pages/HomePage/index.module.scss
- src/components/pages/HomePage/index.tsx
> feat: home > dnd는 어떻게 운영되나요? 섹션 반영

- .gitignore
- .pnp.cjs
- @types/environment.d.ts
- package.json
- src/app/api/index.ts
- src/app/api/model.ts
- src/app/api/projects/route.ts
- src/components/pages/HomePage/index.tsx
- src/utils/index.test.ts
- src/utils/index.ts
- yarn.lock
- install qs, dayjs dependency 설치
- api 구현 및 /projects api route 적용
> feat: api 구현 및 /projects api route 적용

- @types/environment.d.ts
- src/app/api/index.ts
- src/app/api/model.ts
- src/app/api/projects/route.ts
- src/components/molecules/ProjectsSlider/index.tsx
- src/hooks/queries/useGetProjectsQuery.ts
> refactor: api 구조 리팩터링

- src/app/api/projects/route.ts
- src/app/projects/[id]/page.tsx
- src/app/projects/page.tsx
- src/components/pages/ProjectsPage/index.tsx
- src/lib/apis/project.ts
- src/lib/constants/time.ts
> feat: project api 구현 및 캐시 1시간 적용

- src/components/atoms/Button/index.tsx
- src/components/atoms/ProjectCard/index.module.scss
- src/components/atoms/ProjectCard/index.tsx
- src/components/atoms/Tag/index.module.scss
- src/components/atoms/Tag/index.tsx
- src/components/pages/ProjectsPage/index.module.scss
- src/components/pages/ProjectsPage/index.tsx
> feat: project tag 컴포넌트 구현 및 프로젝트 리스트 스타일 수정

- src/app/api/projects/route.ts
- src/app/projects/page.tsx
- src/components/atoms/Button/index.tsx
- src/components/atoms/Tag/Tag.stories.tsx
- src/components/atoms/Tag/index.module.scss
- src/components/atoms/Tag/index.test.tsx
- src/components/atoms/Tag/index.tsx
- src/components/global/TopNavigationMenu/index.tsx
- src/components/molecules/ProjectCard/index.module.scss
- src/components/molecules/Tags/index.module.scss
- src/components/molecules/Tags/index.tsx
- src/components/pages/ProjectsPage/index.module.scss
- src/components/pages/ProjectsPage/index.tsx
- src/lib/apis/project.ts
- src/lib/types/project.ts
> feat: 프로젝트 페이지 param 태그 리스트 적용

- src/app/organizers/[id]/page.tsx
- src/app/organizers/page.tsx
- src/app/projects/[id]/page.tsx
- src/app/projects/page.tsx
- src/components/pages/OrganizersPage/index.module.scss
- src/components/pages/OrganizersPage/index.tsx
- src/lib/apis/organizer.ts
- src/lib/types/organizer.ts
- 빌드시 static page
- 그 외 페이지인 경우 404
> feat: project, organizer static params page 적용

- src/app/jobs/page.tsx
- src/components/atoms/ExternalLink/index.module.scss
- src/components/atoms/ExternalLink/index.tsx
- src/components/molecules/JobCard/index.module.scss
- src/components/molecules/JobCard/index.tsx
- src/components/pages/JobsPage/index.module.scss
- src/components/pages/JobsPage/index.tsx
- src/lib/apis/job.ts
- src/lib/types/job.ts
> feat: jobs 채용 페이지 구현

- package.json
> chore: package.json 라이센스 GPL-3.0-only로 수정

- src/app/api/index.ts
- src/app/api/model.ts
> refactor: remove unused api prefix host url

- .storybook/preview-head.html
- src/stories/Typography.stories.mdx
- src/styles/mixin/text.scss
- src/styles/variables.scss
> style: typography 스토리북에 추가

- src/app/layout.tsx
- src/components/atoms/CounterCard/index.tsx
- src/components/global/GlobalPortal/index.tsx
- src/hooks/useIsMounted.test.ts
- src/hooks/useIsMounted.ts
> feat: portal 세팅 및 useIsMounted적용

- src/components/pages/HomePage/index.tsx
- src/components/templates/ShareAlarmSection/index.tsx
- src/lib/constants/index.ts
> feat: 링크 공유 및 불필요한 섹션 삭제

- .vscode/settings.json
- src/app/organizers/page.tsx
- src/components/atoms/Button/index.module.scss
- src/components/atoms/Button/index.tsx
- src/components/atoms/CounterCard/index.module.scss
- src/components/global/Footer/index.tsx
- src/components/global/TopNavigationMenu/index.module.scss
- src/components/global/TopNavigationMenu/index.tsx
- src/components/molecules/Modal/components/ModalContentsBase/index.module.scss
- src/components/molecules/SponsorSection/index.module.scss
- src/components/molecules/SponsorSection/index.tsx
- src/components/organisms/ShareModal/index.tsx
- src/components/pages/CulturePage/index.module.scss
- src/components/pages/CulturePage/index.tsx
- src/components/pages/HomePage/index.tsx
- src/components/pages/OrganizerPage/index.tsx
- src/components/pages/OrganizersPage/index.module.scss
- src/components/pages/OrganizersPage/index.tsx
- src/components/templates/ShareAlarmSection/index.tsx
- src/lib/apis/organizer.ts
- src/lib/assets/data/organizer_introduction.json
- src/lib/assets/icons/link.svg
- src/lib/types/organizer.ts
> feat: dnd의 도움을 주신 분들 섹션 구현

- src/components/atoms/AccordionItem/index.module.scss
- src/components/atoms/CounterCard/index.module.scss
- src/components/atoms/DetailNavigation/index.module.scss
- src/components/atoms/EventStatusBadge/index.module.scss
- src/components/atoms/ImageCard/index.module.scss
- src/components/atoms/PageTitle/index.module.scss
- src/components/atoms/SectionTitle/index.module.scss
- src/components/atoms/SkillTag/index.module.scss
- src/components/atoms/Tag/index.module.scss
- src/components/global/Footer/index.module.scss
- src/components/global/TopNavigationBar/index.module.scss
- src/components/molecules/JobCard/index.module.scss
- src/components/molecules/Modal/components/ModalContentsBase/index.module.scss
- src/components/molecules/OrganizerCard/index.module.scss
- src/components/molecules/PDFViewer/index.module.scss
- src/components/molecules/ProjectCards/index.module.scss
- src/components/molecules/ProjectsSlider/index.module.scss
- src/components/molecules/SocialIconLink/index.module.scss
- src/components/organisms/ApplyModal/index.module.scss
- src/components/organisms/ShareModal/index.module.scss
- src/components/pages/AboutPage/index.module.scss
- src/components/pages/HomePage/index.module.scss
- src/components/pages/ProjectPage/index.module.scss
- src/styles/global.scss
- src/styles/main.scss
- src/styles/mixin/functions.scss
- src/styles/mixin/responsive.scss
- src/styles/mixin/text.scss
- src/styles/variables.scss
> refactor: sass formatter 적용

- .pnp.cjs
- package.json
- src/app/page.tsx
- src/components/atoms/ScrollElement/index.module.scss
- src/components/atoms/ScrollElement/index.tsx
- src/components/molecules/Modal/components/ModalContentsBase/index.tsx
- src/components/molecules/PDFViewer/index.tsx
- src/components/pages/HomePage/index.tsx
- src/components/pages/ProjectPage/index.module.scss
- src/components/pages/ProjectPage/index.tsx
- src/lib/assets/data/organizers.json
- yarn.lock
- param가 존재하는 경우 스크롤 이동하는 공통 wrapper 컴포넌트 구현
- modal outside 클릭시 닫히는 기능 추가
- 불필요한 use-resize-observer 삭제
- 운영자 데이터 추가
- 프로젝트 pdf가 없을시 이미지로 대체 로직 추가
> feat: param가 존재하는 경우 스크롤 이동하는 공통 wrapper 컴포넌트 구현

- src/components/atoms/ImageCard/index.module.scss
- src/components/atoms/ImageCard/index.tsx
- src/components/atoms/Tag/index.module.scss
- src/components/atoms/Tag/index.tsx
- src/components/molecules/Tags/index.module.scss
- src/components/molecules/Tags/index.tsx
- src/components/pages/AboutPage/index.module.scss
- src/components/pages/AboutPage/index.tsx
- src/components/pages/HomePage/index.module.scss
- src/components/pages/HomePage/index.tsx
- src/components/pages/ProjectsPage/index.tsx
> feat: how to experience dnd 섹션 구현

- src/components/atoms/Tag/Tag.stories.tsx
> fix: 스토릭북 빌드 깨지는 에러 수정

- @types/environment.d.ts
- src/app/api/index.ts
- src/components/global/TopNavigationBar/index.tsx
- src/components/molecules/SponsorSection/index.tsx
- src/components/pages/HomePage/index.tsx
- src/hooks/useClipboard.ts
> refactor: 환경변수 이름 변경

- src/components/atoms/Button/index.module.scss
- src/components/atoms/CounterCard/index.module.scss
- src/components/atoms/CounterCard/index.tsx
- src/components/atoms/ImageCard/index.module.scss
- src/components/atoms/SectionTitle/index.module.scss
- src/components/global/Footer/index.module.scss
- src/components/global/Footer/index.tsx
- src/components/molecules/CounterCardSection/index.module.scss
- src/components/pages/HomePage/index.module.scss
- src/components/templates/ShareAlarmSection/index.module.scss
- src/components/templates/ShareAlarmSection/index.tsx
> style: main page 반응형 적용 및 footer 적용

- src/components/atoms/AccordionItem/index.module.scss
- src/components/atoms/PageTitle/index.module.scss
- src/components/molecules/ProjectCards/index.module.scss
- src/components/molecules/ProjectCards/index.tsx
- src/components/molecules/Tags/index.module.scss
> style: 프로젝트 리스트 페이지 반응형 적용

- src/components/molecules/PDFViewer/index.module.scss
- src/components/pages/ProjectPage/index.module.scss
- src/components/pages/ProjectPage/index.tsx
> style: 프로젝트 상세 페이지 반응형 적용

- src/components/organisms/ReviewList/index.module.scss
- src/components/organisms/ReviewList/index.tsx
> style: 리뷰 페이지 반응형 적용

- src/app/manifest.ts
- src/components/atoms/Tag/index.module.scss
- src/components/molecules/Tags/index.module.scss
- src/components/molecules/Tags/index.tsx
- src/components/templates/GuidelineSection/index.module.scss
- src/components/templates/GuidelineSection/index.tsx
- src/lib/apis/organizer.ts
- src/lib/apis/project.ts
- src/lib/apis/review.ts
- src/lib/assets/data/organizers.json
> fix: 모바일에서 생기는 스타일 깨지는 이슈 수정

- src/components/atoms/ResponsiveMasonry/index.module.scss
- src/components/atoms/ResponsiveMasonry/index.tsx
- src/components/atoms/Tag/index.module.scss
- src/components/atoms/Tag/index.test.tsx
- src/components/atoms/Tag/index.tsx
- src/components/global/ClientProviders/index.tsx
- src/components/global/TopNavigationMenu/index.module.scss
- src/components/molecules/Tags/index.module.scss
- src/components/organisms/ReviewList/index.module.scss
- src/components/organisms/ReviewList/index.tsx
- src/styles/variables.scss
> fix: 모바일 환경에서 동작하지 않는 스타일 수정

- src/app/layout.tsx
> fix: 파비콘 작은 사이즈 안보이는 이슈 수정

- src/components/atoms/SectionTitle/index.module.scss
- src/components/atoms/SkillTag/index.module.scss
- src/components/global/Footer/index.module.scss
- src/components/molecules/JobCard/index.module.scss
- src/components/molecules/OrganizerCards/index.module.scss
- src/components/molecules/ProjectCards/index.module.scss
- src/components/organisms/ReviewList/index.module.scss
- src/components/pages/ProjectPage/index.module.scss
- src/components/templates/ShareAlarmSection/index.module.scss
- src/lib/constants/index.ts
> refactor: 디자인 토큰 정의되어있는대로 폰트 적용 및 모바일에서 깨지는 스타일 수정

- src/app/page.tsx
- src/components/global/Footer/index.tsx
- src/components/molecules/EventStatus/index.tsx
- src/components/organisms/ApplyModal/index.tsx
- src/components/organisms/ApplyNotifyButtonGroup/index.tsx
- src/components/pages/HomePage/index.tsx
- src/components/pages/OrganizerPage/index.tsx
- src/components/templates/ShareAlarmSection/index.tsx
- src/hooks/useCountdown.ts
- src/hooks/useCurrentTime.ts
- src/lib/apis/event.ts
- src/lib/assets/data/current_applicant_count.json
- src/lib/assets/data/event_status.json
- src/lib/assets/data/index.ts
- src/lib/constants/index.ts
- src/lib/types/event.ts
- 이벤트 상태 추가
- 실시간 카운트 기능 추가
- 알람 기능 추가
> feat: 이벤트 상태에 따른 실시간 카운트 기능 구현

- src/lib/assets/data/total_count_status.json
> chore: update applicant count

- src/components/molecules/CounterCardSection/index.tsx
> fix: 이탈자수 잘못된 기수 수정

- src/components/atoms/Button/index.tsx
- src/components/global/Footer/index.tsx
- src/components/global/TopNavigationMenu/index.tsx
- src/components/molecules/Tags/index.tsx
- src/components/organisms/ApplyNotifyButtonGroup/index.tsx
- src/components/pages/OrganizerPage/index.tsx
- src/components/pages/ProjectsPage/index.tsx
- src/lib/apis/organizer.ts
- src/lib/assets/data/organizers.json
> refactor: 리뷰사항 반영 및 next 링크에 에니메이션 적용

- src/components/molecules/OrganizerCards/index.module.scss
- src/components/pages/OrganizerPage/index.module.scss
> style: update boxshadow color in OrganizerCards and OrganizerPage

- src/components/organisms/ApplyNotifyButtonGroup/index.tsx
- src/hooks/useCountdown.ts
> fix: fix countdown display issue in ApplyNotifyButtonGroup

- src/components/atoms/Button/index.tsx
- src/components/pages/OrganizerPage/index.tsx
> feat: add isAnimated prop to Button component

- src/lib/assets/data/organizers.json
This commit adds two new mentors, 차주희 and 강하나, to the organizers.json file.
> chore: add new mentors to organizers.json

- src/components/pages/OrganizersPage/index.tsx
- src/lib/assets/data/organizers.json
> chore: 운영진 이미지 추가 및 운영진 링크 아이콘 제거

- src/app/_fonts/index.ts
- src/app/layout.tsx
- src/styles/global.scss
> fix: 버튼에 폰트가 제대로 적용되지 않는 이슈 수정

- .github/workflows/ci.yml
> ci: update CI workflow to cache install, build packages

- .github/workflows/ci.yml
> ci: update CI workflow to cache build packages

- apps/admin/src/components/auth/SignIn/index.tsx
- apps/admin/src/components/auth/SignOut/index.tsx
- apps/web/src/components/global/Footer/index.tsx
- apps/web/src/components/molecules/Modal/components/ModalContentsBase/index.tsx
- apps/web/src/components/molecules/PDFViewer/index.tsx
- apps/web/src/components/molecules/SponsorSection/index.tsx
- apps/web/src/components/organisms/ApplyModal/index.tsx
- apps/web/src/components/organisms/ApplyNotifyButtonGroup/index.tsx
- apps/web/src/components/pages/CulturePage/index.tsx
- apps/web/src/components/pages/HomePage/index.tsx
- apps/web/src/components/pages/OrganizerPage/index.tsx
- apps/web/src/components/pages/OrganizersPage/index.tsx
- apps/web/src/components/pages/ProjectPage/index.tsx
- apps/web/src/components/templates/ShareAlarmSection/index.tsx
- packages/ui/src/client.ts
- packages/ui/src/components/client.ts
- packages/ui/src/components/index.ts
> refactor: move Button component to @dnd-academy/ui package

- packages/core/.eslintrc.js
- packages/core/.gitignore
- packages/core/package.json
- packages/core/src/api/index.ts
- packages/core/src/index.ts
- packages/core/src/utils/index.ts
- packages/core/tsconfig.json
- packages/core/vite.config.mts
- packages/ui/vite.config.mts
- yarn.lock
> feat: packages에 @dnd-academy/core 초기 세팅 적용

- .github/workflows/ci.yml
- .lintstagedrc.json
- package.json
- packages/eslint-config/package.json
- turbo.json
> chore: turbo setting 최적화 및 ci 수정

- apps/web/src/components/molecules/Modal/components/ModalContentsBase/index.tsx
- apps/web/src/components/molecules/Modal/components/ModalOpenButton/index.tsx
- apps/web/src/components/molecules/Modal/components/ModalProvider/index.tsx
> refactor: modal useContext 공통화 적용

- apps/admin/@types/environment.d.ts
- apps/admin/src/actions/count.ts
- apps/admin/src/app/page.tsx
- apps/web/src/components/organisms/CounterCardSection/index.tsx
- packages/core/src/@types/count.ts
> feat(admin): total count status 수정 액션 구현

- apps/web/.storybook/preview-head.html
- apps/web/package.json
- apps/web/src/components/molecules/Modal/components/ModalContentsBase/index.tsx
- apps/web/src/components/molecules/Modal/components/ModalOpenButton/index.tsx
- apps/web/src/components/molecules/Modal/components/ModalProvider/index.tsx
- apps/web/src/components/organisms/SponsorSection/index.tsx
- yarn.lock
> chore: pdfjs-dist 파일 삭제 및 storybook font 적용 수정, modal 리팩터링

- apps/admin/src/components/TotalCountStatusForm/index.tsx
- apps/admin/src/components/common/SubmitButton/index.tsx
> refactor(admin): submit button 적용

- apps/admin/src/actions/count.ts
- apps/admin/src/app/current-applicant-count/page.module.scss
- apps/admin/src/app/current-applicant-count/page.tsx
- apps/admin/src/components/CurrentApplicantCountForm/index.module.scss
- apps/admin/src/components/CurrentApplicantCountForm/index.tsx
- apps/admin/src/components/Navigator/index.tsx
> feat(admin): current-applicant-count form 페이지 적용

- apps/admin/@types/environment.d.ts
- apps/admin/src/auth.ts
> fix: auth secret 추가

- apps/admin/@types/environment.d.ts
- apps/admin/src/actions/count.ts
- apps/admin/src/app/api/cron/current-applicant-count/route.ts
- apps/admin/src/app/api/current-applicant-count/route.ts
- apps/admin/src/app/api/handler.ts
- apps/admin/src/app/current-applicant-count/page.tsx
- apps/web/@types/environment.d.ts
- apps/web/src/app/api/revalidate/route.ts
- apps/web/src/lib/constants/time.ts
- apps/web/src/middleware.ts
> chore: admin에서 수정사항 반영 후 web api revalidated 시키는 로직 구현

- apps/admin/src/app/api/handler.ts
> fix: revalidate web fetch의 url이 잘못 들어가있어 에러가 나는 이슈 수정

- apps/admin/src/app/api/handler.ts
> fix: revalidate web fetch의 url이 잘못 들어가있어 에러가 나는 이슈 수정 (#178)

- apps/web/src/components/molecules/SocialIconLink/index.tsx
> perf(web): social icon 링크에 인식 가능한 이름 aria-label 적용

- apps/web/src/components/molecules/SocialIconLink/index.tsx
> perf(web): social icon 링크에 인식 가능한 이름 aria-label 적용 (#180)

- apps/web/src/components/organisms/CounterCardSection/index.tsx
- apps/web/src/components/pages/HomePage/index.tsx
- apps/web/src/lib/assets/data/event_status.json
> chore: 11기 종료로 인한 상태 업데이트

- apps/web/src/components/organisms/CounterCardSection/index.tsx
- apps/web/src/components/pages/HomePage/index.tsx
- apps/web/src/lib/assets/data/event_status.json
> chore: 11기 종료로 인한 상태 업데이트 (#184)

- apps/admin/@types/environment.d.ts
- apps/admin/src/app/api/blob/latest/[name]/route.ts
- apps/admin/src/app/api/handler.ts
- apps/admin/src/app/current-applicant-count/page.tsx
- apps/admin/src/app/total-count-status/page.tsx
> fix: blob token 이슈 수정

- apps/admin/src/app/current-applicant-count/page.tsx
- apps/admin/src/app/total-count-status/page.tsx
- apps/admin/src/components/common/ServerErrorBoundary/index.tsx
- apps/admin/src/utils/index.ts
> chore(admin): server component에 header 사용 제거

- apps/admin/src/app/current-applicant-count/page.tsx
- apps/admin/src/app/total-count-status/page.tsx
- apps/admin/src/components/common/ServerErrorBoundary/index.tsx
- apps/admin/src/utils/index.ts
Reverts DNDACADEMY/dnd-academy-v2#190
> Revert "Revert "chore(admin): server component에 header 사용 제거""

- apps/web/src/app/api/blob/latest/[name]/route.ts
- apps/web/src/app/page.tsx
- apps/web/src/components/organisms/CounterCardSection/index.tsx
> fix(web): blob 에러 이슈 수정

- apps/admin/src/app/current-applicant-count/page.tsx
- apps/admin/src/app/total-count-status/page.tsx
> fix: admin blob url이 달라서 빌드이후 404떨어지는 이슈

- apps/admin/src/app/current-applicant-count/page.tsx
- apps/admin/src/app/total-count-status/page.tsx
> fix: admin blob url이 달라서 빌드이후 404떨어지는 이슈 (#196)

- README.md
> docs: readme의 블로그 글 링크 수정

- apps/admin/next-env.d.ts
- apps/web/src/lib/assets/data/projects.json
- apps/web/src/lib/assets/data/reviews.json
> chore: 11기 프로젝트 및 리뷰 추가

- apps/web/src/lib/assets/data/projects.json
> chore: 11th pdf data 추가

- apps/web/src/app/projects/[id]/page.tsx
- apps/web/src/components/organisms/ProjectCards/index.tsx
- apps/web/src/components/organisms/ProjectsSlider/index.tsx
- apps/web/src/components/pages/ProjectPage/index.tsx
- apps/web/src/lib/assets/data/organizers.json
- packages/core/src/@types/project.ts
> fix: 프로젝트  thumbnail 없는 케이스 적용

- apps/web/src/components/organisms/ProjectCards/index.tsx
- apps/web/src/components/organisms/ProjectsSlider/index.tsx
- apps/web/src/components/pages/ProjectPage/index.tsx
- apps/web/src/lib/assets/data/projects.json
- packages/core/src/@types/project.ts
> feat: dnd 11기 프로젝트 thumbnail, pdf 추가

- apps/web/src/lib/assets/data/projects.json
> fix: same key props rendering 이슈 수정 (#209)

- apps/web/src/components/molecules/PDFViewer/index.module.scss
- apps/web/src/components/molecules/PDFViewer/index.tsx
> feat(web): pdf 로딩시 progress bar 로딩중 상태 추가

- apps/web/src/components/molecules/PDFViewer/index.module.scss
- apps/web/src/components/molecules/PDFViewer/index.tsx
> feat(web): pdf 로딩시 progress bar 로딩중 상태 추가 (#211)

- .github/workflows/ci.yml
> fix: ci build시 깨지는 이슈 수정

- apps/admin/src/app/total-count-status/page.tsx
- apps/web/src/components/organisms/CounterCardSection/index.tsx
- apps/web/src/components/pages/HomePage/index.tsx
- packages/ui/src/components/molecules/CounterCard/CounterCard.stories.tsx
- packages/ui/src/components/molecules/CounterCard/index.module.scss
- packages/ui/src/components/molecules/CounterCard/index.test.tsx
- packages/ui/src/components/molecules/CounterCard/index.tsx
- packages/ui/src/styles/variables.scss
- count card 컴포넌트 크리스마스 theme 적용
- 크리스마스 컬러 토큰 적용
> feat: count card 컴포넌트 크리스마스 theme 적용

- apps/web/src/components/global/ClientProviders/index.tsx
> chore: 눈 내리는 눈 개수 수정

- apps/web/src/components/global/ClientProviders/index.tsx
> chore: 화면 크기에 따라서 눈 양 조정

- apps/web/src/components/organisms/CounterCardSection/index.tsx
> fix: 이탈자 기수 이전기수로 수정

- packages/ui/src/components/molecules/Button/index.tsx
> fix: motion deprecated warning 수정

- packages/ui/src/components/molecules/Button/index.tsx
> fix: motion deprecated warning 수정 (#244)

- apps/web/src/components/molecules/Modal/components/ModalContentsBase/index.module.scss
- apps/web/src/components/molecules/Modal/components/ModalContentsBase/index.tsx
> style: 모달 아래서 위로 뜨는 애니메이션 추가

- .github/workflows/ci.yml
> ci: job_generate_applicant_count 파이프라인 추가

- .github/workflows/ci.yml
- apps/web/scripts/generate-applicant-count.ts
> fix: ci job_generate_applicant_count pipeline

- .yarnrc.yml
- apps/admin/package.json
- apps/web/package.json
- apps/web/src/components/atoms/ClientOnly/index.tsx
- apps/web/src/components/pages/HomePage/index.tsx
- packages/ui/package.json
> fix: yarn packageExtensions로 변경 & event status hydration 에러 수정

- apps/web/src/components/organisms/EventStatus/index.tsx
- apps/web/src/lib/assets/data/event_status.json
> fix: 모집 발표 일자 수정

- apps/web/src/components/organisms/EventStatus/index.tsx
- apps/web/src/lib/assets/data/event_status.json
> fix: 모집 발표 일자 수정 (#269)

- apps/web/src/lib/assets/data/total_count_status.json
> chore: 총 참여자수 업데이트

- .vscode/settings.json
- apps/web/src/lib/assets/data/event_status.json
> chore: 합격자발표 시간 변경

- .vscode/settings.json
- apps/web/src/lib/assets/data/event_status.json
> chore: 합격자발표 시간 변경 (#274)

- apps/web/src/components/organisms/EventStatus/index.tsx
- apps/web/src/lib/assets/data/event_status.json
- packages/core/src/@types/event.ts
> chore: active 이벤트 상태 추가 (#276)

- apps/web/next.config.js
> fix: 비용 이슈로 이미지 최적화 제거

- apps/web/next.config.js
> fix: 비용 이슈로 이미지 최적화 제거 (#286)

- apps/web/src/components/organisms/CounterCardSection/index.tsx
- apps/web/src/lib/assets/data/event_status.json
- apps/web/src/lib/constants/index.ts
> chore: 13기 일정 홈페이지 상태 업데이트 (#292)

- apps/web/src/components/organisms/PassboardButton/index.tsx
- apps/web/src/components/pages/HomePage/index.tsx
- apps/web/src/lib/apis/analytics.ts
- apps/web/src/lib/constants/gaEvent.ts
> feat: passboard analitics 추가

- apps/web/src/components/organisms/PassboardButton/index.tsx
- apps/web/src/components/pages/HomePage/index.tsx
- apps/web/src/lib/apis/analytics.ts
- apps/web/src/lib/constants/gaEvent.ts
> feat: passboard analitics 추가 (#302)

- apps/web/src/lib/apis/analytics.ts
> fix: analytics 수정

- apps/web/src/lib/assets/data/organizers.json
> chore: 운영진 정보 업데이트

- apps/web/src/lib/assets/data/organizers.json
> chore: 운영진 정보 업데이트 (#306)

- apps/web/src/lib/assets/data/event_status.json
> chore: event 정보수정

- apps/web/src/lib/assets/data/event_status.json
> chore: event 정보수정 (#308)

- apps/web/src/components/pages/HomePage/index.tsx
- apps/web/src/lib/assets/data/event_status.json
> fix: passboardButton 제거

- apps/web/src/components/pages/HomePage/index.tsx
- apps/web/src/lib/assets/data/event_status.json
> fix: passboardButton 제거 (#312)

- apps/web/src/lib/assets/data/event_status.json
> feat: 13기 종료상태 변경
